spring:
  application:
    name: USER-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/PractoUser
    username: root
    password: Sush#25293
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
server:
  port: 8082

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
      management:
        health:
          circuitbreakers:
            enabled: true
        endpoints:
          web:
            exposure:
              include: health


  cloud:
    loadbalancer:
      ribbon:
        eureka:
          enabled: true
        endpoint:
          health:
            show-details: always

      resilience4j:
        circuitbreaker:
           instances:
              postBreaker:
              registerHealthIndicator: true
              eventConsumerBufferSize: 10
              failureRateThreshold: 50
              minimumNumberOfCalls: 5
              automaticTransitionFromOpenToHalfOpenEnabled: true
              waitDurationInOpenState: 6s
              permittedNumberOfCallsInHalfOpenState: 3
              slidingWindowSize: 10
              slidingWindowType: COUNT_BASED
           doctorBreaker:
              registerHealthIndicator: true
              eventConsumerBufferSize: 10
              failureRateThreshold: 50
              minimumNumberOfCalls: 5
              automaticTransitionFromOpenToHalfOpenEnabled: true
              waitDurationInOpenState: 6s
              permittedNumberOfCallsInHalfOpenState: 3
              slidingWindowSize: 10
              slidingWindowType: COUNT_BASED
              medicineBreaker:
                registerHealthIndicator: true
                eventConsumerBufferSize: 10
                failureRateThreshold: 50
                minimumNumberOfCalls: 5
                automaticTransitionFromOpenToHalfOpenEnabled: true
                waitDurationInOpenState: 6s
                permittedNumberOfCallsInHalfOpenState: 3
                slidingWindowSize: 10
                slidingWindowType: COUNT_BASED
              bookingBreaker:
                registerHealthIndicator: true
                eventConsumerBufferSize: 10
                failureRateThreshold: 50
                minimumNumberOfCalls: 5
                automaticTransitionFromOpenToHalfOpenEnabled: true
                waitDurationInOpenState: 6s
                permittedNumberOfCallsInHalfOpenState: 3
                slidingWindowSize: 10
                slidingWindowType: COUNT_BASED
                reviewBreaker:
                  registerHealthIndicator: true
                  eventConsumerBufferSize: 10
                  failureRateThreshold: 50
                  minimumNumberOfCalls: 5
                  automaticTransitionFromOpenToHalfOpenEnabled: true
                  waitDurationInOpenState: 6s
                  permittedNumberOfCallsInHalfOpenState: 3
                  slidingWindowSize: 10
                  slidingWindowType: COUNT_BASED
